### ISSUE TITLE
你好，感受很深，不错不错，大佬可以集成页面，在页面配置规则，直接生效吗

### ISSUE THREAD

**Issue by lovo1** [sunpeak/riskcontrol#7]
你好，感受很深，不错不错，大佬可以集成页面，在页面配置规则，直接生效吗？  页面配置的规则，与实际规则生效，可以联动起来，大佬可以给一个demo 吗

**Comment by sunpeak** [comment]
目前只提供api接口的方式

**Comment by sunpeak** [comment]
目前只提供api接口的方式
